[project]
name = "extra-2025"
description = "Extra 2025"
version = "2025"
authors = [
    {name = "Oscar Llorente", email = "ollorente@comillas.edu"},
]
readme = "README.md"
requires-python = "==3.11.*"

[tool.black]
line-length = 88
exclude = '''
/(
  \.venv
)/
'''

[tool.flake8]
max-line-length = 88
extend-ignore = "E203, W503"
exclude = [
    ".venv/",
]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
exclude = [
    ".venv/",
]
cache_dir = "/dev/null"

[tool.pylint]
max-line-length = 88
disable = "R0801,R0912,R0913,R0914,R0915,R0917,R1711,R1732,W1203,R0902,W0707,C0114"

[tool.pylint.MASTER]
ignore-paths = [
    ".venv/",
]

[tool.pylint.typecheck]
generated-members=["numpy.*", "torch.*"]